### ISSUE TITLE
Regarding the dimension of query and key

### ISSUE THREAD

**Issue by netw0rkf10w** [csrhddlam/axial-deeplab#11]
Hi,

I observed in the code that the query's and key's dimensions are haft of the value's (`out_planes // 2`, `group_planes // 2`). Is there a specific reason for that (apart making it faster)?

Thanks.

**Comment by netw0rkf10w** [comment]
@csrhddlam Thanks. I guess "one" is supposed to give the best accuracy? Do you have an estimate of how better it is compared to "half"?

**Comment by csrhddlam** [comment]
Yes, more channels usually leads to better accuracy, but we did not study much about it. Personally, I won't expect much improvement by switching from "half" to "one".

**Comment by netw0rkf10w** [comment]
Thanks for the answer.
