### ISSUE TITLE
Question on paper COCO panoptic segmentation results

### ISSUE THREAD

**Issue by lxtGH** [csrhddlam/axial-deeplab#13]
Hi! It is a very nice and  very solid work.  I have some questions about this paper.

Since you use Panoptic-DeepLab frame work, first semantic segmentation then instance groupinng. 
I want to know what is the mIoU and mAp improvement on COCO compared with Panoptic-DeepLab baseline ?

Also, what are the advantages using axial attention layers over ASPP module in Panoptic Deeplab?

Thanks a lot !

**Comment by csrhddlam** [comment]
Thanks!

1. We didn't (have the script to) evaluate these two metrics. In addition, COCO usually evaluate stuff-only semantic segementation, or instance segmentation with allowed overlapping masks. These are not that well aligned with panoptic segmentation metrics.

2. It captures larger, and dynamic context. And table 6 shows numerical comparisons.

**Comment by lxtGH** [comment]
I means it can capture more small objects segmentation ? Since COCO has various small stuff.

**Comment by csrhddlam** [comment]
Yes, axial-attention can capture both small and large objects, though we didn't evaluate it. Fig 4 could be helpful if you're interested in its robustness to scales.

**Comment by lxtGH** [comment]
Aslo, for panoptic deeplab it shows the most important things are semantic segmentation results rather prediction instance center. What is semantic segmentation results using axial-deeplab ?

**Comment by csrhddlam** [comment]
I'm not sure if I understand your question, but please refer to Table 4, 5, 6, 7, or 9, mIoU column for semantic segmentation results
