### ISSUE TITLE
Segmentation

### ISSUE THREAD

**Issue by SwagatRanjit84** [csrhddlam/axial-deeplab#14]
Hi I am writing a paper for segmentation using axial deeplab. Can you please provide a rough sketch of the encoder and decoder for this network to use for segmentation?

**Comment by csrhddlam** [comment]
Hi, the modifications needed to turn Axial-ResNet into Axial-DeepLab is described in 3.2 [Axial-DeepLab](https://arxiv.org/pdf/2003.07853.pdf). The decoder is sketched in [Panoptic-DeepLab](https://arxiv.org/abs/1911.10194), whose code is available [here](https://github.com/bowenc0221/panoptic-deeplab)

**Comment by SwagatRanjit84** [comment]
Can this repo be used for the encoder part to my segmentation model or do I have to make changes to it?

**Comment by csrhddlam** [comment]
If your image is not large, then yes, it can be directly used.

If your image is large, then possibly no, due to memory issues. You might want to implement the local version with a span of 65 described in the paper. This will reduce memory footprint at lower levels.

Another option is to use conv in lower stages and apply axial-deeplab in higher stages.

**Comment by SwagatRanjit84** [comment]
In the encoder part should we take all layer1, layer2, layer3, layer4 ( which will have 1024 channels) and then send it to decoder 
or
 as shown in your paper, the figure of decoder takes 256 channels input so should we take only layer1 and layer2 from which we get 256 channels and then use this 256 channel and fed it into decoder?

**Comment by csrhddlam** [comment]
Our main model uses convolutional decoder (as described in 3.2 [Axial-DeepLab](https://arxiv.org/pdf/2003.07853.pdf)). Please refer to Figure 2 of [Panoptic-DeepLab](https://arxiv.org/pdf/1911.10194.pdf) for more details.

**Comment by SwagatRanjit84** [comment]
Hi,
 Your paper states :

Firstly, to extract dense feature maps, DeepLab [13] changes the stride and
atrous rates of the last one or two stages in ResNet [32]. Similarly, we
remove the stride of the last stage but we do not implement the ‘atrous’
attention module, since our axial-attention already captures global
information for the whole input. In this work, we extract feature maps with
output stride (i.e., the ratio of input resolution to the final backbone
feature resolution) 16. We do not pursue output stride 8, since it is
computationally expensive.


By similarly do you mean you used the same Axial-ResNet as an encoder for
the segmentation task by only changing the last stage and not implementing
the atrous attention module,

or did you mean you used Resnet 50 as an encoder and used the proposed
axial-attention after the last layer (instead of stride of the last
stage and instead of the atrous attention module) before passing it in the
decoder?


Best regards,

Swagat

**Comment by csrhddlam** [comment]
We used the same Axial-ResNet as an encoder for the segmentation task by only changing the last stage and not implementing the atrous attention module. 

i.e. all bottleneck blocks are using axial-attention, in our segmentation models.

**Comment by SwagatRanjit84** [comment]
As far as I have understood:
1. You used the "Axial-ResNet as an encoder for the segmentation task by only changing the last stage and not implementing the atrous attention module" as in this repo, but how many blocks do you use while using the segmentation block before going to the decoder block. Do we use these all layers in the segmentation block also?

<img width="861" alt="layers" src="https://user-images.githubusercontent.com/31880242/96428314-5ab48c00-121f-11eb-9a37-c774b70be7a7.png">

**Comment by csrhddlam** [comment]
Yes, we always use all the layers in the encoder.

**Comment by DesertsP** [comment]
> Yes, we always use all the layers in the encoder.

And during fine-tune process, what is the size of the input? How do you deal with position coding？

**Comment by csrhddlam** [comment]
The input is for example 1025 * 1025, and the span is fixed at 65 as mentioned in the paper. The positional encoding is still a fix-size set of vectors.

**Comment by DesertsP** [comment]
This is inconsistent with the implementation here, right? And no pertained model released?

**Comment by csrhddlam** [comment]
This repo currently only supports ImageNet classification with the "Conv-Stem + Axial-Attention" backbone. The pretrained model has been released for classification.

Segmentation is not supported and contribution will be appreciated.

**Comment by lkqnaruto** [comment]
> If your image is not large, then yes, it can be directly used.
> 
> If your image is large, then possibly no, due to memory issues. You might want to implement the local version with a span of 65 described in the paper. This will reduce memory footprint at lower levels.
> 
> Another option is to use conv in lower stages and apply axial-deeplab in higher stages.

I wonder what does it mean when you say "lower stages" and "higher stages"?
