### ISSUE TITLE
Seems dist_train.py didn't wrap the model with the synchronize batch norm

### ISSUE THREAD

**Issue by dongdongbh** [csrhddlam/axial-deeplab#18]
Am I understood right? The model wasn't wrapped by the synchronize batch norm in dist_train.py. Will this affect the results?

**Comment by phj128** [comment]
Yes, we do not support SyncBN. In our setting, I don't think it would be a big difference.

**Comment by dongdongbh** [comment]
> Yes, we do not support SyncBN. In our setting, I don't think it would be a big difference.

Thanks for your reply~
