### ISSUE TITLE
Confused about the `transpose` in positional encoding of key

### ISSUE THREAD

**Issue by dongdongbh** [csrhddlam/axial-deeplab#19]
https://github.com/csrhddlam/axial-deeplab/blob/fe1d0523faa7b3068ee59ab13f222a46c511d0aa/lib/models/axialnet.py#L67
I'm a bit confused about this transposision. After reading the issue #17, I kind of understood it, but if the key should be transposed, then why the value shouldn't?

In addition, I noticed that there is a scaler `1/sqrt(n)` after multiplication of `q` and `v` in the original Transformer model, but the scaler is removed here, why?

**Comment by csrhddlam** [comment]
In our implementation, the similarity matrix has the shape of [batch, group or head, query length, key length]. In our case, the query length equals to the key length, but the query axis is always before the key axis. This implementation choice determines whether we transpose q, k and v. As shown in this v example, we sum over the last key dimension, and predict a vector for each query position.

https://github.com/csrhddlam/axial-deeplab/blob/fe1d0523faa7b3068ee59ab13f222a46c511d0aa/lib/models/axialnet.py#L74

`1/sqrt(n)` is replaced by batch norm which has a similar normalizing effect, as we discussed in the paper. BN removes the need for this careful initializations or scalings, and BN works well in practice.
