### ISSUE TITLE
how does axial-attention support multi-scale training/testing?

### ISSUE THREAD

**Issue by Jensen-Su** [csrhddlam/axial-deeplab#22]
It seems that the number of parameters of axial-attention module depends on the input feature size (because of the `kernel_size` should equal to H/W).  Then how does it support variable input sizes?

**Comment by csrhddlam** [comment]
For panoptic segmentation, we use a fixed span (or kernel size) of 65x65 as mentioned in the paper. This repo was for ImageNet classification only, so we did not implement the local span version.
