### ISSUE TITLE
What's HERE??

### ISSUE THREAD

**Issue by wanghao9610** [csrhddlam/axial-deeplab#24]
https://github.com/csrhddlam/axial-deeplab/blob/fe1d0523faa7b3068ee59ab13f222a46c511d0aa/lib/models/utils.py#L4

**Comment by csrhddlam** [comment]
I believe this is meant for possible customized initializations.
https://github.com/csrhddlam/axial-deeplab/blob/fe1d0523faa7b3068ee59ab13f222a46c511d0aa/lib/models/axialnet.py#L176
https://github.com/csrhddlam/axial-deeplab/blob/fe1d0523faa7b3068ee59ab13f222a46c511d0aa/lib/models/axialnet.py#L90
