### ISSUE TITLE
It seems that the code of qkv_transform is missing. 

### ISSUE THREAD

**Issue by Nicholasxin** [csrhddlam/axial-deeplab#26]
It seems that the code of class qkv_transform is not completed in lib/utils.py. Please provide the completed code. Thanks a lot!

**Comment by csrhddlam** [comment]
This repo contains a completed code that runs.

qkv_transform is just simply a convolution, but with customized initialization:
https://github.com/csrhddlam/axial-deeplab/blob/master/lib/models/axialnet.py#L176
