### ISSUE TITLE
About  local constraints 

### ISSUE THREAD

**Issue by YLFF** [csrhddlam/axial-deeplab#30]
I'm sorry if i understand the code in a wrong way, did this repo implement the local constraints part for larger input size?
I assume that the AxialAttention Module can only accept the input feature map size which equals to _kernel_size*kernel_size_ , am i right?

**Comment by phj128** [comment]
Yes. This repo does not implement local axial attention. So the module only support the feature map size which is kernel_size * kernel_size.

**Comment by YLFF** [comment]
Yes, thank you for answering!
