### ISSUE TITLE
size error

### ISSUE THREAD

**Issue by shrutishrestha** [csrhddlam/axial-deeplab#8]
I got this error while executing training. What could be the cause of this .
<img width="1266" alt="Screen Shot 2020-09-10 at 6 19 35 PM" src="https://user-images.githubusercontent.com/33342277/92729637-57adbc80-f392-11ea-8241-0465c3be9784.png">

**Comment by LeeVinteuil** [comment]
Have you solved the problem? When I run, the same problem occurs

**Comment by evinpinar** [comment]
I guess it is a pytorch version issue and can be solved by modifying einsum letters, but not sure?
