### ISSUE TITLE
model train error

### ISSUE THREAD

**Issue by shrutishrestha** [csrhddlam/axial-deeplab#9]
I was training this network by my dataset but I got an error. What could be the cause of this?
<img width="1543" alt="Screen Shot 2020-09-10 at 7 45 28 PM" src="https://user-images.githubusercontent.com/33342277/92741656-8fbafc80-f39e-11ea-9453-a508b1357869.png">

**Comment by csrhddlam** [comment]
The cause is CUDA out of memory. You could try reducing the batch size or using a GPU with larger memory.
